periodics:
- name: periodic-cluster-api-provider-azure-capi-e2e-v1beta1-release-1-15
  cluster: eks-prow-build-cluster
  decorate: true
  decoration_config:
    timeout: 4h
  interval: 72h
  labels:
    preset-dind-enabled: "true"
    preset-kind-volume-mounts: "true"
    preset-azure-community: "true"
  extra_refs:
    - org: kubernetes-sigs
      repo: cluster-api-provider-azure
      base_ref: release-1.15
      path_alias: "sigs.k8s.io/cluster-api-provider-azure"
  spec:
    containers:
    - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20240725-1d8ea3e909-1.29
      command:
        - runner.sh
      args:
        - ./scripts/ci-e2e.sh
      env:
        - name: GINKGO_FOCUS
          value: "Cluster API E2E tests"
        - name: GINKGO_SKIP
          value: "\\[K8s-Upgrade\\]|API Version Upgrade"
      resources:
        limits:
          cpu: 2
          memory: 4Gi
        requests:
          cpu: 2
          memory: 4Gi
      # docker-in-docker needs privileged mode
      securityContext:
        privileged: true
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-cluster-api-provider-azure
    testgrid-tab-name: capz-periodic-capi-e2e-v1beta1-release-1-15
    testgrid-alert-email: k8s-infra-staging-cluster-api-azure@kubernetes.io
- name: periodic-cluster-api-provider-azure-e2e-v1beta1-release-1-15
  cluster: eks-prow-build-cluster
  decorate: true
  decoration_config:
    timeout: 4h
  interval: 72h
  labels:
    preset-dind-enabled: "true"
    preset-kind-volume-mounts: "true"
    preset-azure-community: "true"
  extra_refs:
    - org: kubernetes-sigs
      repo: cluster-api-provider-azure
      base_ref: release-1.15
      path_alias: "sigs.k8s.io/cluster-api-provider-azure"
  spec:
    containers:
    - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20240725-1d8ea3e909-1.29
      command:
        - runner.sh
      args:
        - ./scripts/ci-e2e.sh
      env:
        - name: GINKGO_FOCUS
          value: "Workload cluster creation"
        - name: GINKGO_SKIP
          value: \[Managed Kubernetes\]
      resources:
        limits:
          cpu: 2
          memory: 4Gi
        requests:
          cpu: 2
          memory: 4Gi
      # docker-in-docker needs privileged mode
      securityContext:
        privileged: true
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-cluster-api-provider-azure
    testgrid-tab-name: capz-periodic-e2e-v1beta1-release-1-15
    testgrid-alert-email: k8s-infra-staging-cluster-api-azure@kubernetes.io
- name: periodic-cluster-api-provider-azure-e2e-aks-v1beta1-release-1-15
  cluster: eks-prow-build-cluster
  decorate: true
  decoration_config:
    timeout: 4h
  interval: 72h
  labels:
    preset-dind-enabled: "true"
    preset-kind-volume-mounts: "true"
    preset-azure-community: "true"
  extra_refs:
    - org: kubernetes-sigs
      repo: cluster-api-provider-azure
      base_ref: release-1.15
      path_alias: "sigs.k8s.io/cluster-api-provider-azure"
  spec:
    containers:
    - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20240725-1d8ea3e909-1.29
      command:
        - runner.sh
      args:
        - ./scripts/ci-e2e.sh
      env:
        - name: GINKGO_FOCUS
          value: \[Managed Kubernetes\]
        - name: GINKGO_SKIP
          value: ""
      resources:
        limits:
          cpu: 2
          memory: 4Gi
        requests:
          cpu: 2
          memory: 4Gi
      # docker-in-docker needs privileged mode
      securityContext:
        privileged: true
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-cluster-api-provider-azure
    testgrid-tab-name: capz-periodic-e2e-aks-v1beta1-release-1-15
    testgrid-alert-email: k8s-infra-staging-cluster-api-azure@kubernetes.io
