periodics:
# This job is used as a heartbeat health check of the Prow instance's ability to run jobs.
# Alerts expect it to run every 5 mins and will fire after 20 mins without a successful run.
# Please keep this in sync with the `pull-test-infra-prow-checkconfig` job
- name: ci-test-infra-prow-checkconfig
  interval: 5m
  cluster: eks-prow-build-cluster
  decorate: true
  extra_refs:
  - org: kubernetes
    repo: test-infra
    base_ref: master
  spec:
    containers:
    - image: gcr.io/k8s-prow/checkconfig:v20240723-dbbd2d86b
      command:
      - checkconfig
      args:
      - --config-path=config/prow/config.yaml
      - --job-config-path=config/jobs
      - --plugin-config=config/prow/plugins.yaml
      - --strict
      - --warnings=mismatched-tide-lenient
      - --warnings=tide-strict-branch
      - --warnings=needs-ok-to-test
      - --warnings=validate-owners
      - --warnings=missing-trigger
      - --warnings=validate-urls
      - --warnings=unknown-fields
      - --warnings=duplicate-job-refs
      - --warnings=unknown-fields-all
      - --warnings=non-decorated-jobs
      - --warnings=valid-decoration-config
      resources:
        requests:
          cpu: "1"
          memory: "2Gi"
        limits:
          cpu: "1"
          memory: "2Gi"
  annotations:
    testgrid-dashboards: sig-testing-misc
    testgrid-alert-email: kubernetes-sig-testing-alerts@googlegroups.com, k8s-infra-prow-oncall@kubernetes.io
    testgrid-num-failures-to-alert: '10'
